spring：
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.197:1521:x3db2007
    username: HTTDBA
    password: HTTGROUP
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

