oracle:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.0.124:1521:x3db2007
    username: HTTDBA
    Password: HTTGROUP
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
